package controller;
import model.*; import org.springframework.data.domain.Page; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.mvc.support.RedirectAttributes; import repository.StateRepository; import service.*; import java.util.*;
@Controller public class BisIsiController {
 private static final Set<String> EXCLUDED_STATES=Set.of("vaishali","paschim medinipur","narora","natwar","kenmore");
 private final BisIsiService service; private final OperationAccessService access; private final StateRepository states; private final BisIsiExcelService excel; private final ConvertedLeadOperationSyncService leadSync; private final DomesticFilesService domesticFiles;
 public BisIsiController(BisIsiService service,OperationAccessService access,StateRepository states,BisIsiExcelService excel,ConvertedLeadOperationSyncService leadSync,DomesticFilesService domesticFiles){this.service=service;this.access=access;this.states=states;this.excel=excel;this.leadSync=leadSync;this.domesticFiles=domesticFiles;}
 @GetMapping({"/operation","/operation/index"}) public String operationRoot(){return "redirect:/operation/bis-isi";}
 @GetMapping("/operation/bis-isi") public String index(Authentication a,Model m,@RequestParam(required=false)@org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE)java.time.LocalDate startDate,@RequestParam(required=false)@org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE)java.time.LocalDate endDate,@RequestParam(required=false)String procedure,@RequestParam(required=false)Boolean extras,@RequestParam(required=false)Long engineer,@RequestParam(required=false)Long creator,@RequestParam(required=false)String status,@RequestParam(required=false)String search,@RequestParam(required=false)List<String> process,@RequestParam(required=false)String analyticsProcess,@RequestParam(required=false)Integer analyticsYear,@RequestParam(defaultValue="0")int page){User u=access.require(a);leadSync.sync();List<String> selectedProcesses=process==null?List.of():process.stream().filter(BisIsiService.STATUSES::contains).distinct().limit(1).toList();String selectedAnalyticsProcess=BisIsiService.STATUSES.contains(analyticsProcess)?analyticsProcess:"License Granted";int selectedAnalyticsYear=analyticsYear!=null?analyticsYear:(startDate!=null?startDate.getYear():(endDate!=null?endDate.getYear():java.time.Year.now().getValue()));Page<BisIsiOperation> result=service.list(u,startDate,endDate,procedure,extras,engineer,creator,status,search,selectedProcesses,page);common(m,u);m.addAttribute("operations",result);m.addAttribute("operationStatuses",service.resolvedStatuses(result.getContent()));m.addAttribute("dashboard",service.dashboard(u,startDate,endDate,engineer,creator,selectedProcesses));m.addAttribute("statusCards",service.statusCards(u,startDate,endDate,engineer,creator));m.addAttribute("monthlyAnalytics",service.monthlyAnalytics(u,selectedAnalyticsYear,startDate,endDate,engineer,creator,selectedProcesses,selectedAnalyticsProcess));m.addAttribute("analyticsYears",service.analyticsYears(u,engineer,creator));m.addAttribute("analyticsYear",selectedAnalyticsYear);m.addAttribute("analyticsProcess",selectedAnalyticsProcess);m.addAttribute("selectedProcesses",selectedProcesses);m.addAttribute("startDate",startDate);m.addAttribute("endDate",endDate);m.addAttribute("procedure",procedure);m.addAttribute("extras",extras);m.addAttribute("engineerFilter",engineer);m.addAttribute("creatorFilter",creator);m.addAttribute("statusFilter",status);m.addAttribute("search",search);return "operation/bis-isi/index";}
 public record SearchSuggestion(String value, String detail) {}
 @GetMapping("/operation/bis-isi/suggestions") @ResponseBody public List<SearchSuggestion> suggestions(Authentication a,@RequestParam String query){
  User user=access.require(a);String term=query.trim();if(term.isEmpty())return List.of();
  Map<String,SearchSuggestion> matches=new LinkedHashMap<>();
  for(BisIsiOperation operation:service.list(user,null,null,null,null,null,null,null,term,0).getContent()){
   String detail=operation.getCompanyName()+" · "+operation.getIndianStandard();
   for(String value:new String[]{operation.getCompanyName(),operation.getClientName(),operation.getIndianStandard()}){
    if(value!=null&&value.toLowerCase(Locale.ROOT).contains(term.toLowerCase(Locale.ROOT)))matches.putIfAbsent(value.toLowerCase(Locale.ROOT),new SearchSuggestion(value,detail));
    if(matches.size()>=8)return List.copyOf(matches.values());
   }
  }
  return List.copyOf(matches.values());
 }
 @GetMapping("/operation/bis-isi/create") public String create(Authentication a,Model m){User u=access.require(a);common(m,u);BisIsiOperation operation=new BisIsiOperation();operation.setOperationDate(java.time.LocalDate.now());m.addAttribute("operation",operation);m.addAttribute("editing",false);return "operation/bis-isi/form";}
 @GetMapping("/operation/bis-isi/{id}/edit") public String edit(Authentication a,@PathVariable long id,Model m){User u=access.require(a);BisIsiOperation o=service.get(u,id);if(!serviceAccess(u,o))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.FORBIDDEN);common(m,u);m.addAttribute("operation",o);m.addAttribute("editing",true);return "operation/bis-isi/form";}
 @PostMapping("/operation/bis-isi/save") public String save(Authentication a,@ModelAttribute BisIsiOperation form,@RequestParam(required=false)Long id,RedirectAttributes flash){User u=access.require(a);try{BisIsiOperation saved=service.save(u,form,id);flash.addFlashAttribute("success",id==null?"BIS-ISI operation created successfully.":"BIS-ISI operation updated successfully.");return "redirect:/operation/bis-isi";}catch(IllegalArgumentException e){flash.addFlashAttribute("error",e.getMessage());return id==null?"redirect:/operation/bis-isi/create":"redirect:/operation/bis-isi/"+id+"/edit";}}
 @PostMapping("/operation/bis-isi/{id}/status") public ResponseEntity<Void> status(Authentication a,@PathVariable long id,@RequestParam String projectStatus){try{service.updateStatus(access.require(a),id,projectStatus);return ResponseEntity.noContent().build();}catch(IllegalArgumentException e){return ResponseEntity.badRequest().build();}}
 @PostMapping("/operation/bis-isi/{id}/payment") public String payment(Authentication a,@PathVariable long id,@RequestParam String paymentStatus,@RequestParam String advancePaymentStatus){service.updatePayments(access.require(a),id,paymentStatus,advancePaymentStatus);return "redirect:/operation/bis-isi";}
 @GetMapping("/operation/bis-isi/{id}/action-details") @ResponseBody public Map<String,Object> actionDetails(Authentication a,@PathVariable long id){BisIsiOperation o=service.get(access.require(a),id);Map<String,Object> result=new LinkedHashMap<>();result.put("paymentStatus",o.getPaymentStatus());result.put("advancePaymentStatus",o.getAdvancePaymentStatus());result.put("paymentRemark",o.getPaymentRemark());result.put("createdAt",o.getCreatedAt());result.put("updatedAt",o.getUpdatedAt());result.put("createdBy",o.getCreatedBy());return result;}
 @PostMapping("/operation/bis-isi/{id}/advance-payment") public Object advancePayment(Authentication a,@PathVariable long id,@RequestParam String advancePaymentStatus,@RequestHeader(value="X-Requested-With",required=false)String requestedWith,RedirectAttributes flash){try{service.updateAdvancePayment(access.require(a),id,advancePaymentStatus);if("XMLHttpRequest".equals(requestedWith))return ResponseEntity.noContent().build();flash.addFlashAttribute("success","Advance payment status updated successfully.");}catch(IllegalArgumentException e){if("XMLHttpRequest".equals(requestedWith))return ResponseEntity.badRequest().body(Map.of("message",e.getMessage()));flash.addFlashAttribute("error",e.getMessage());}return "redirect:/operation/bis-isi";}
 @PostMapping("/operation/bis-isi/{id}/payment-details") public Object paymentDetails(Authentication a,@PathVariable long id,@RequestParam String paymentStatus,@RequestParam(required=false)String paymentRemark,@RequestHeader(value="X-Requested-With",required=false)String requestedWith,RedirectAttributes flash){try{service.updatePaymentDetails(access.require(a),id,paymentStatus,paymentRemark);if("XMLHttpRequest".equals(requestedWith))return ResponseEntity.noContent().build();flash.addFlashAttribute("success","Payment details updated successfully.");}catch(IllegalArgumentException e){if("XMLHttpRequest".equals(requestedWith))return ResponseEntity.badRequest().body(Map.of("message",e.getMessage()));flash.addFlashAttribute("error",e.getMessage());}return "redirect:/operation/bis-isi";}
 @PostMapping("/operation/bis-isi/bulk-assign") public String bulk(Authentication a,@RequestParam List<Long> selectedIds,@RequestParam Long engineerId,RedirectAttributes flash){try{service.bulkAssign(access.require(a),selectedIds,engineerId);flash.addFlashAttribute("success",selectedIds.size()+" operation"+(selectedIds.size()==1?"":"s")+" assigned successfully.");}catch(IllegalArgumentException e){flash.addFlashAttribute("error",e.getMessage());}return "redirect:/operation/bis-isi";}
 @PostMapping("/operation/bis-isi/{id}/delete") public String delete(Authentication a,@PathVariable long id,RedirectAttributes flash){try{service.delete(access.require(a),id);flash.addFlashAttribute("success","BIS-ISI operation deleted successfully.");}catch(IllegalArgumentException e){flash.addFlashAttribute("error",e.getMessage());}return "redirect:/operation/bis-isi";}
 @PostMapping("/operation/bis-isi/bulk-delete") public String bulkDelete(Authentication a,@RequestParam(required=false)List<Long> selectedIds,RedirectAttributes flash){try{int deleted=service.bulkDelete(access.require(a),selectedIds);flash.addFlashAttribute("success",deleted+" BIS-ISI operation"+(deleted==1?"":"s")+" deleted successfully.");}catch(IllegalArgumentException e){flash.addFlashAttribute("error",e.getMessage());}return "redirect:/operation/bis-isi";}
 @GetMapping("/operation/bis-isi/domestic-files") @ResponseBody public List<DomesticFilesService.FileEntry> domesticFiles(Authentication a){access.require(a);return domesticFiles.list();}
 @GetMapping("/operation/bis-isi/domestic-files/{id}/download") public ResponseEntity<org.springframework.core.io.Resource> downloadDomesticFile(Authentication a,@PathVariable int id){access.require(a);DomesticFilesService.FileEntry file=domesticFiles.get(id);org.springframework.core.io.Resource resource=domesticFiles.resource(id);String type=file.name().toLowerCase(Locale.ROOT).endsWith(".xlsx")?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":file.name().toLowerCase(Locale.ROOT).endsWith(".docx")?"application/vnd.openxmlformats-officedocument.wordprocessingml.document":"application/msword";return ResponseEntity.ok().cacheControl(org.springframework.http.CacheControl.noStore()).header(HttpHeaders.CONTENT_DISPOSITION,org.springframework.http.ContentDisposition.attachment().filename(file.name(),java.nio.charset.StandardCharsets.UTF_8).build().toString()).contentType(MediaType.parseMediaType(type)).body(resource);}
 @GetMapping("/operation/bis-isi/simplified/download") public ResponseEntity<org.springframework.core.io.Resource> downloadSimplified(Authentication a){access.require(a);org.springframework.core.io.Resource resource=domesticFiles.simplifiedResource();return ResponseEntity.ok().cacheControl(org.springframework.http.CacheControl.noStore()).header(HttpHeaders.CONTENT_DISPOSITION,org.springframework.http.ContentDisposition.attachment().filename("simplified.docx",java.nio.charset.StandardCharsets.UTF_8).build().toString()).contentType(MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.wordprocessingml.document")).body(resource);}
 @PostMapping("/operation/bis-isi/import") public String importExcel(Authentication a,@RequestParam MultipartFile file,RedirectAttributes flash){try{var r=excel.importFile(access.require(a),file);flash.addFlashAttribute("success",r.imported()+" BIS-ISI operations imported; "+r.skipped()+" skipped.");if(!r.errors().isEmpty())flash.addFlashAttribute("error",String.join(" | ",r.errors()));}catch(IllegalArgumentException e){flash.addFlashAttribute("error",e.getMessage());}return "redirect:/operation/bis-isi";}
 @GetMapping(value="/operation/bis-isi/export",produces="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet") public ResponseEntity<byte[]> exportExcel(Authentication a,@RequestParam(required=false)@org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE)java.time.LocalDate startDate,@RequestParam(required=false)@org.springframework.format.annotation.DateTimeFormat(iso=org.springframework.format.annotation.DateTimeFormat.ISO.DATE)java.time.LocalDate endDate,@RequestParam(required=false)String procedure,@RequestParam(required=false)Boolean extras,@RequestParam(required=false)Long engineer,@RequestParam(required=false)Long creator,@RequestParam(required=false)String status,@RequestParam(required=false)String search){byte[] data=excel.export(access.require(a),startDate,endDate,procedure,extras,engineer,creator,status,search);String filename="bis-isi-operations-"+java.time.LocalDate.now()+".xlsx";return ResponseEntity.ok().cacheControl(org.springframework.http.CacheControl.noStore()).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+filename+"\"").contentType(MediaType.parseMediaType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")).contentLength(data.length).body(data);}
 private void common(Model m,User u){List<User> engineers=service.engineers();List<User> creators=service.creators();m.addAttribute("activePage","operation-bis-isi");m.addAttribute("statuses",BisIsiService.STATUSES);m.addAttribute("engineers",engineers);m.addAttribute("assignmentUsers",service.assignmentUsers());m.addAttribute("engineerNames",engineers.stream().collect(java.util.stream.Collectors.toMap(User::getId,User::getName,(a,b)->a)));m.addAttribute("creators",creators);m.addAttribute("creatorNames",creators.stream().collect(java.util.stream.Collectors.toMap(User::getId,User::getName,(a,b)->a)));m.addAttribute("states",states.findByCountryIdOrderByNameAsc(101).stream().filter(state->state.getName()!=null&&!EXCLUDED_STATES.contains(state.getName().toLowerCase(java.util.Locale.ROOT))).toList());m.addAttribute("operationAdmin",access.isAdmin(u));m.addAttribute("canAccessOperation",true);}
 private boolean serviceAccess(User u,BisIsiOperation o){return access.isAdmin(u)||u.getId().equals(o.getCreatedBy())||u.getId().equals(o.getAssignedEngineerId());}
}
